[[servers]]
listen = "127.0.0.1:25565"
hosts = [
    { hostname = "localhost", target = "127.0.0.1:25566" },
    { hostname = "localhost.localdomain", target = "127.0.0.1:25567" },
]

[[servers]]
listen = "127.0.0.1:8080"
redirect = "127.0.0.1:80"
